backend:
  name: github
  repo: galorichie/my-portfolio # Change to your repo
  branch: master # Or main
  base_url: https://YOUR-DECAPBRIDGE-URL # From DecapBridge setup

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.html"
        label: "Homepage Content"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Intro Text", name: "intro", widget: "text" }
