backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"   # where images will be stored in the repo
public_folder: "/images/uploads" # how they’ll be served on the site

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "About Section", name: "about", widget: "string" }
