backend:
  name: git-gateway
  branch: master

media_folder: "aycollection" # Path inside your repo where uploaded files will go
public_folder: "/aycollection" # How to access those files publicly (this was missing)

media_library:
  name: uploadcare
  config: {} # This is okay as a placeholder

collections:
  - name: "products"
    label: "Products"
    folder: "aycollection"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Description"
        name: "description"
        widget: "text"
